export const theme = {
  colors: {
    primary: '#EC5F5F',
    textColorBlack: '#303030',
    textColorGray: '#8C8C8C',
    textColorWhite: '#ffffff',
    blueColor: '#0082CD',
    backgroundColor: '#FFFFFF',
    black: '#000000',
    inputTextBackground: '#F6F7FA',
    passwordIconColor: '#9D9FA0',
    onlineColor: '#4ED442',
    pointsColor: '#FCD034',
    tosqa: '#4DC9D1',
    purple: '#8D5EF2',
    omlette: '#FCCC75',
  },
  fontFamilyWeight: {
    Regular: 'Poppins-Regular',
    Black: 'Poppins-Black',
    Bold: 'Poppins-Bold',
    ExtraBold: 'Poppins-ExtraBold',
    ExtraLight: 'Poppins-ExtraLight',
    Italic: 'Poppins-Italic',
    Light: 'Poppins-Light',
    Medium: 'Poppins-Medium',
    SemiBold: 'Poppins-SemiBold',
    Thin: 'Poppins-Thin',
  },
};
